#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["onnx>=1.14", "numpy>=1.24"]
# ///
"""Generate a prototype ONNX depth-map defect detector for the synthetic wall fixture.

Model spec
----------
Input:   "image"  float32 [1, 1, 32, 32]
         Normalised depth values in [0, 1].  No-data pixels are encoded as 1.0
         (far background), so values near 0 indicate objects close to the sensor.

Output:  "boxes"  float32 [1, 5]
         [u0_norm, v0_norm, u1_norm, v1_norm, confidence] in [0, 1].
         Coordinates are normalised; multiply by image width/height to get pixels.

Detection logic
---------------
A pixel is a "defect candidate" when its normalised depth < 0.15 (close to sensor).
The model computes the tight bounding box of all defect-candidate pixels and reports
the fraction of pixels that qualify as confidence.

This is a rule-based ONNX graph — no training required.  It works correctly on the
synthetic wall fixture generated by `eds inspect generate-fixtures` because the 20 mm
bulge (closest to the camera) normalises to ~0.0 while the flat wall normalises to
~0.91.

Usage
-----
    uv run scripts/generate_prototype_model.py \\
        --out crates/edgesentry-inspect/tests/fixtures/prototype_detector.onnx
"""
import argparse
import struct
import numpy as np
import onnx
from onnx import helper, TensorProto, numpy_helper

MODEL_W: int = 32
MODEL_H: int = 32
THRESHOLD: float = 0.15   # pixels below this are defect candidates
N_PIXELS: float = float(MODEL_W * MODEL_H)


def build_model() -> onnx.ModelProto:
    # ── Coordinate grids (constants baked into the model) ──────────────────
    # u_grid[row, col] = col / (MODEL_W - 1)  →  normalised x in [0, 1]
    # v_grid[row, col] = row / (MODEL_H - 1)  →  normalised y in [0, 1]
    u_grid = np.tile(
        np.arange(MODEL_W, dtype=np.float32) / (MODEL_W - 1),
        (MODEL_H, 1),
    )
    v_grid = np.tile(
        (np.arange(MODEL_H, dtype=np.float32) / (MODEL_H - 1)).reshape(MODEL_H, 1),
        (1, MODEL_W),
    )

    initializers = [
        numpy_helper.from_array(np.float32(THRESHOLD), name="threshold"),
        numpy_helper.from_array(np.float32(1.0),       name="one"),
        numpy_helper.from_array(np.float32(1.0),       name="large"),
        numpy_helper.from_array(np.float32(N_PIXELS),  name="n_pixels"),
        numpy_helper.from_array(u_grid,                name="u_grid"),
        numpy_helper.from_array(v_grid,                name="v_grid"),
        numpy_helper.from_array(np.array([0, 1], dtype=np.int64), name="axes_01"),
        numpy_helper.from_array(np.array([1],    dtype=np.int64), name="shape_scalar_to_1d"),
        numpy_helper.from_array(np.array([0],    dtype=np.int64), name="axes_unsqueeze"),
    ]

    nodes = [
        # ── Squeeze [1,1,32,32] → [32,32] ──────────────────────────────────
        helper.make_node("Squeeze", inputs=["image", "axes_01"], outputs=["img_2d"]),

        # ── Defect mask: img_2d < threshold ─────────────────────────────────
        helper.make_node("Less", inputs=["img_2d", "threshold"], outputs=["defect_bool"]),
        helper.make_node(
            "Cast",
            inputs=["defect_bool"],
            outputs=["defect_f"],
            to=TensorProto.FLOAT,
        ),

        # ── Confidence = sum(defect_f) / n_pixels ──────────────────────────
        helper.make_node(
            "ReduceSum",
            inputs=["defect_f"],
            outputs=["sum_defect"],
            keepdims=0,
            noop_with_empty_axes=0,
        ),
        helper.make_node("Div", inputs=["sum_defect", "n_pixels"], outputs=["confidence_s"]),

        # ── u1 = ReduceMax(defect_f * u_grid) ───────────────────────────────
        helper.make_node("Mul", inputs=["defect_f", "u_grid"], outputs=["u_max_in"]),
        helper.make_node(
            "ReduceMax",
            inputs=["u_max_in"],
            outputs=["u1_s"],
            keepdims=0,
            noop_with_empty_axes=0,
        ),

        # ── v1 = ReduceMax(defect_f * v_grid) ───────────────────────────────
        helper.make_node("Mul", inputs=["defect_f", "v_grid"], outputs=["v_max_in"]),
        helper.make_node(
            "ReduceMax",
            inputs=["v_max_in"],
            outputs=["v1_s"],
            keepdims=0,
            noop_with_empty_axes=0,
        ),

        # ── not_defect = 1 - defect_f ────────────────────────────────────────
        helper.make_node("Sub", inputs=["one", "defect_f"], outputs=["not_defect_f"]),

        # ── u0 = ReduceMin(u_grid + not_defect * large) ─────────────────────
        # Non-defect pixels get pushed to (u + 1.0) which is always > any defect u.
        helper.make_node("Mul", inputs=["not_defect_f", "large"], outputs=["u_bg"]),
        helper.make_node("Add", inputs=["u_grid",   "u_bg"],      outputs=["u_for_min"]),
        helper.make_node(
            "ReduceMin",
            inputs=["u_for_min"],
            outputs=["u0_s"],
            keepdims=0,
            noop_with_empty_axes=0,
        ),

        # ── v0 = ReduceMin(v_grid + not_defect * large) ─────────────────────
        helper.make_node("Mul", inputs=["not_defect_f", "large"], outputs=["v_bg"]),
        helper.make_node("Add", inputs=["v_grid",   "v_bg"],      outputs=["v_for_min"]),
        helper.make_node(
            "ReduceMin",
            inputs=["v_for_min"],
            outputs=["v0_s"],
            keepdims=0,
            noop_with_empty_axes=0,
        ),

        # ── Reshape each scalar to [1] ───────────────────────────────────────
        helper.make_node(
            "Reshape", inputs=["u0_s", "shape_scalar_to_1d"], outputs=["u0_1d"]
        ),
        helper.make_node(
            "Reshape", inputs=["v0_s", "shape_scalar_to_1d"], outputs=["v0_1d"]
        ),
        helper.make_node(
            "Reshape", inputs=["u1_s", "shape_scalar_to_1d"], outputs=["u1_1d"]
        ),
        helper.make_node(
            "Reshape", inputs=["v1_s", "shape_scalar_to_1d"], outputs=["v1_1d"]
        ),
        helper.make_node(
            "Reshape", inputs=["confidence_s", "shape_scalar_to_1d"], outputs=["conf_1d"]
        ),

        # ── Concat [u0, v0, u1, v1, conf] → [5] ─────────────────────────────
        helper.make_node(
            "Concat",
            inputs=["u0_1d", "v0_1d", "u1_1d", "v1_1d", "conf_1d"],
            outputs=["boxes_1d"],
            axis=0,
        ),

        # ── Unsqueeze [5] → [1, 5] ───────────────────────────────────────────
        # opset-13 Unsqueeze takes axes as a second input tensor; axes=[0] gives [1, 5].
        helper.make_node(
            "Unsqueeze",
            inputs=["boxes_1d", "axes_unsqueeze"],
            outputs=["boxes"],
        ),
    ]

    input_info  = helper.make_tensor_value_info(
        "image", TensorProto.FLOAT, [1, 1, MODEL_H, MODEL_W]
    )
    output_info = helper.make_tensor_value_info(
        "boxes", TensorProto.FLOAT, [1, 5]
    )

    graph = helper.make_graph(
        nodes,
        "depth_defect_detector",
        [input_info],
        [output_info],
        initializer=initializers,
    )

    model = helper.make_model(
        graph,
        opset_imports=[helper.make_opsetid("", 18)],
    )
    model.doc_string = (
        "Prototype depth-map defect detector for the EdgeSentry synthetic wall fixture. "
        "Input: float32 [1,1,32,32] normalised depth (no-data=1.0). "
        "Output: float32 [1,5] normalised bbox [u0,v0,u1,v1,confidence]."
    )
    onnx.checker.check_model(model)
    return model


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="Output .onnx path")
    args = parser.parse_args()

    model = build_model()

    import pathlib
    pathlib.Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    onnx.save(model, args.out)

    size = pathlib.Path(args.out).stat().st_size
    print(f"Prototype model written to {args.out!r}  ({size:,} bytes)")

    # Quick self-test: run the model on a synthetic defect image.
    try:
        import onnxruntime as ort
        sess = ort.InferenceSession(args.out)
        img = np.ones((1, 1, MODEL_H, MODEL_W), dtype=np.float32) * 0.91
        # Place a 6×6 dark patch in the centre (like the fixture defect)
        cy, cx = MODEL_H // 2, MODEL_W // 2
        img[0, 0, cy - 3:cy + 3, cx - 3:cx + 3] = 0.0
        boxes = sess.run(None, {"image": img})[0]
        print(f"Self-test output: {boxes}")
        print("Self-test passed.")
    except ImportError:
        print("onnxruntime not available — skipping self-test.")


if __name__ == "__main__":
    main()
