name: Dependency Submission

on:
  push:
    branches: ["main"]

permissions: {}

jobs:
  dependency-submission:
    name: Submit dependency snapshot
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3

      - name: Submit dependency snapshot
        uses: advanced-security/component-detection-dependency-submission-action@9c110eb34dee187cd9eca76a652b9f6a0ed22927  # v0.1.1
